import { db } from "./firebase-config.js";
import {
ref,
get
} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-database.js";

const params = new URLSearchParams(window.location.search);

const regNumber = params.get("reg");

if (!regNumber) {
alert("Registration Number Missing");
}

const applicationsRef = ref(db, "applications");

get(applicationsRef).then((snapshot) => {

```
if (!snapshot.exists()) {
    return;
}

let found = false;

snapshot.forEach((child) => {

    const data = child.val();

    if (data.regNumber === regNumber) {

        found = true;

        if (!data.certificateGenerated) {

            document.querySelector(".certificate").innerHTML = `
                <h1>Certificate Not Available</h1>
                <p>
                This certificate has not yet been generated by Sir Mean Academy.
                </p>
            `;

            return;
        }

        document.getElementById("studentName").textContent =
            data.fullName || "";

        document.getElementById("courseName").textContent =
            data.course || "";

        document.getElementById("regNumber").textContent =
            data.regNumber || "";

        document.getElementById("completionDate").textContent =
            data.certificateDate || "";
    }

});

if (!found) {

    document.querySelector(".certificate").innerHTML = `
        <h1>Invalid Registration Number</h1>
        <p>No student record found.</p>
    `;
}
```

});
